#+TITLE: Analisis de los datasets
#+AUTHOR: Grupo 42
#+OPTIONS: toc:nil

* Analisis de los datasets
** Datasets usados:
+ Aparcamiento de motos
+ Barrios
+ Calles
+ Estacionamiento bicicletas
** Datos a utilizar:
|                | Descripcion                                    | Observaciones                                                    |
| districtName   | Nombre del distrito                            |                                                                  |
| geoPosition    | Posicion geolocalizada con latitud y longitud  | Util para encontrar las estaciones mas cercanas                  |
| idEstacion     | ID de la estacion                              |                                                                  |
| lastUpdated    | Ultima vez que los datos han sido actualizados | Servira para saber si los datos puede que esten desactualizado-s |
| nCapacidad     | Capacidad maxima de la estacion                |                                                                  |
| noCalle        | Nombre comun de la calle                       |                                                                  |
| slotsAvaliable | Puestos disponibles en la estacion             | Gracias a esto se sabra si se podra aparcar                      |
** Licencia

El Excmo. Ayuntamiento de Zaragoza informa a los usuari@s que esta sede electrónica está gestionada por la Oficina Web Municipal, perteneciente a la Dirección General de Ciencia y Tecnología del Excmo. Ayuntamiento de Zaragoza. La información y los contenidos que se proporcionan en esta sede electrónica son facilitados por los diferentes Servicios y Departamentos Municipales.

En cumplimiento con lo dispuesto en el artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico, se informa que www.zaragoza.es es un nombre de dominio, cuyo titular es el Excmo. Ayuntamiento de Zaragoza, el cual, a través de su sede electrónica proporciona servicios, actividades y actuaciones dentro de su ámbito de actuación relacionados con servicios de la sociedad de la información. A efectos de lo dispuesto en el mencionado artículo 10, los datos de la entidad son los siguientes:

    Nombre: Excmo. Ayuntamiento de Zaragoza
    Dirección: Edificio Seminario: Vía Hispanidad nº 20, 50071 Zaragoza
    CIF: P5030300G
    Teléfono: 976 721 000
    Fax: 976 721 166
    Email: webmunicipal@zaragoza.es

Este Aviso Legal regula las condiciones de uso de la sede electrónica www.zaragoza.es. Toda persona que acceda a la misma asume el papel de usuari@, comprometiéndose a la observancia y cumplimiento de las disposiciones incluidas en ella así como su correcta utilización de conformidad con la legislación aplicable, respondiendo de los perjuicios que pudiera ocasionar el incumplimiento de esta obligación. El tratamiento de los datos de carácter personal que se realice a través de esta sede electrónica se sujetará a lo establecido por la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal y demás normativa de aplicación, tal como se dispone en la "Política de Privacidad" contenida en la misma.
*** Propiedad Intelectual e Industrial

Los derechos de propiedad intelectual pertenecen al Excmo. Ayuntamiento de Zaragoza, por tanto, esta sede electrónica y todos sus contenidos, textos, imágenes, gráficos, audio y cualesquiera otros materiales son propiedad del Excmo. Ayuntamiento de Zaragoza. Las marcas o signos distintivos del Excmo. Ayuntamiento de Zaragoza contenidos en la sede electrónica están protegidos por la legislación de propiedad industrial. Los diseños, logotipos, texto y/o gráficos ajenos al Excmo. Ayuntamiento de Zaragoza que pudieran aparecer en la misma pertenecen a sus respectivos propietarios, siendo ellos responsables de cualquier posible controversia que pudiera suscitarse respecto a los mismos.
*** Condiciones de uso
**** CONDICIONES GENERALES
El acceso a la sede electrónica del Excmo. Ayuntamiento de Zaragoza así como el uso que pueda hacerse de la información que se contiene en la misma, son de la exclusiva responsabilidad del usuari@. El usuari@ se obliga a acceder a la sede electrónica y a usar sus contenidos de forma diligente, correcta y lícita y, en particular, se compromete a hacer uso de las informaciones y/o servicios ofrecidos de conformidad con la normativa vigente en cada momento. El Excmo. Ayuntamiento de Zaragoza no se hará responsable en ningún caso del uso que los usuari@s y/o terceros pudieran hacer de su sede electrónica o de sus contenidos, ni de los daños y perjuicios que pudieran derivarse del mismo, incluidos daños informáticos o virus. El Excmo. Ayuntamiento de Zaragoza excluye toda responsabilidad por cualquier daño o perjuicio en el software o hardware del usuari@ que pudiera derivarse del acceso a esta sede electrónica, así como de su uso, transmisión, difusión, almacenamiento de información o aplicaciones contenidas en la misma. El Excmo. Ayuntamiento de Zaragoza podrá efectuar, en cualquier momento y sin necesidad de previo aviso, las modificaciones y actualizaciones necesarias sobre la información contenida en su sede electrónica. El funcionamiento de la misma está constantemente revisado al objeto de que funcione correctamente los 365 días del año. No obstante, no se descarta la posibilidad de que existan ciertos errores de programación o acontezcan causas de fuerza mayor, catástrofes naturales o circunstancias semejantes que hagan imposible, en un momento dado, el acceso a su sede electrónica. El Excmo. Ayuntamiento de Zaragoza desarrollará los esfuerzos precisos para evitar errores y, en su caso, repararlos o actualizarlos lo antes posible, excluyendo toda responsabilidad por los daños y perjuicios causados por las interrupciones o fallos temporales en el acceso a la misma.
**** CONDICIONES ESPECÍFICAS PARA LA UTILIZACIÓN DE LA PLATAFORMA GOBIERNO ABIERTO
***** Condiciones aplicables

El uso de la plataforma Gobierno Abierto del Ayuntamiento de Zaragoza está sujeta a las condiciones de uso y a la política de privacidad de la Web Municipal, además de a las siguientes condiciones específicas, cuyo objetivo es garantizar que los ciudadanos y ciudadanas puedan enviar sus comentarios, aportaciones y propuestas, así como hacer uso de los canales participativos que ofrece la plataforma, realizándose todo ello dentro de un marco de respeto y legalidad.
***** Finalidad

El usuario se compromete a hacer un uso de la plataforma adecuado con su finalidad participativa y a no emplearlo para incurrir en actividades ilícitas; contrarias a la buena fe; que vulneren o transgredan el honor, la intimidad personal o familiar o la imagen de las personas; o que supongan actos de competencia desleal o publicidad ilícita.
***** Responsabilidad sobre los contenidos aportados

El Usuario es el único responsable de los contenidos, comentarios y ficheros que pueda poner a disposición a través de la plataforma. El Ayuntamiento de Zaragoza excluye toda responsabilidad por los daños y perjuicios de cualquier naturaleza que puedan derivar de los contenidos aportados por los usuarios, así como por las opiniones vertidas por los mismos.

El usuario adquiere una obligación de veracidad sobre los contenidos que aporte a la plataforma, por la que se compromete a no incurrir en falta de veracidad, exactitud, exhaustividad, pertinencia y/o actualidad de los contenidos.

El usuario se obliga a no publicar (o subir) ningún fichero que esté sujeto a derechos de propiedad intelectual o industrial de terceros, salvo que el titular de dichos derechos le haya otorgado una licencia o autorización formal.
***** Moderación de los contenidos

La plataforma dispone de un sistema de moderación de comentarios, aportaciones y propuestas cuya finalidad es evitar la publicación de contenidos que infrinjan las presentes Condiciones o cualquier otra regulación que resulte aplicable. El usuario acepta que los contenidos aportados sean supervisados por el Ayuntamiento de Zaragoza y, en su caso, retirados de la plataforma. En caso de disconformidad, el usuario podrá dirigirse al Ayuntamiento por medio de los mecanismos disponibles en la Web Municipal, o por cualquier otro que legalmente resulte adecuado.

Las aportaciones que, por parte del Ayuntamiento de Zaragoza, se considere que no entran en la categoría de comentario, aportaciones o propuestas, por tratarse de una queja, sugerencia o solicitud de información serán derivadas al Servicio de Quejas y Sugerencias para su oportuna tramitación y/o resolución.
***** Comunicaciones con los usuarios

El Usuario acepta expresamente que la dirección de correo electrónico que, en su caso, haya aportado para las comunicaciones con el Ayuntamiento es correcta y veraz, y que las comunicaciones dirigidas a la misma se considerarán eficaces a todos los efectos.
**** CONDICIONES GENERALES PARA LA MOVILIDAD GENERAL DE PUESTA A DISPOSICIÓN DE LOS DOCUMENTOS REUTILIZABLES DEL AYUNTAMIENTO DE ZARAGOZA
***** Obligatoriedad de las condiciones generales

Las presentes condiciones generales, disponibles con carácter permanente bajo Aviso Legal, obligan a cualquier agente reutilizador por el mero hecho de hacer uso de los documentos sometidos a ellas.
***** Autorización de reutilización y cesión no exclusiva de derechos de propiedad intelectual

Las presentes condiciones generales permiten la reutilización de los documentos sometidos a ellas para fines comerciales y no comerciales. Se entiende por reutilización el uso de documentos que obran en poder del Ayuntamiento de Zaragoza y de los demás organismos y entidades incluidos en el ámbito subjetivo de la Ordenanza de Administración Electrónica por su artículo 2, por personas físicas o jurídicas, con fines comerciales o no comerciales, siempre que dicho uso no constituya una actividad administrativa pública. Por ejemplo, la reutilización autorizada incluye actividades como la copia, difusión, modificación, adaptación, extracción, reordenación y combinación de la información.

Se entiende por documento electrónico, según el artículo 50 de la mencionada Ordenanza, cualquier representación de texto, imagen, sonido o video, o las combinaciones de todos o alguno de estos elementos, que haya sido codificada mediante el empleo de un programa de tratamiento de la información y resulte legible gracias al mismo programa usado para su generación u otro equivalente, siendo susceptible de tratamiento individualizado. Además, a los efectos de estas condiciones generales se incluyen expresamente las bases y colecciones de datos.

La reutilización conlleva la cesión gratuita y no exclusiva de los derechos de propiedad intelectual, en su caso, correspondientes a tales documentos, autorizándose la realización de actividades de reproducción, distribución, comunicación pública o transformación, que sean necesarias para desarrollar la actividad de reutilización autorizada, en cualquier modalidad y bajo cualquier formato, para todo el mundo y por el plazo máximo permitido por la Ley.
***** Condiciones generales para la reutilización

Se aplican las siguientes condiciones generales para la reutilización de los documentos:

- Está prohibido desnaturalizar el sentido de la información.
- Debe citarse la fuente de los documentos objeto de la reutilización. Esta cita podrá realizarse de la siguiente manera: "Origen de los datos: Ayuntamiento de Zaragoza (o, en su caso, órgano administrativo, organismo o entidad de que se trate)".
- Debe mencionarse la fecha de la última actualización de los documentos objeto de la reutilización, siempre cuando estuviera incluida en el documento original.
- No se podrá indicar, insinuar o sugerir que el Ayuntamiento de Zaragoza participa, patrocina o apoya la reutilización que se lleve a cabo con la información.
- Deben conservarse, no alterarse ni suprimirse los metadatos sobre la fecha de actualización y las condiciones de reutilización aplicables incluidos, en su caso, en el documento puesto a disposición para su reutilización.
***** Exclusión de responsabilidad

La utilización de los conjuntos de datos se realizará por parte de los usuarios o agentes de la reutilización bajo su propia cuenta y riesgo, correspondiéndoles en exclusiva a ellos responder frente a terceros por daños que pudieran derivarse de ella.

El Ayuntamiento de Zaragoza no será responsable del uso que de su información hagan los agentes reutilizadores ni tampoco de los daños sufridos o pérdidas económicas que, de forma directa o indirecta, produzcan o puedan producir perjuicios económicos, materiales o sobre datos, provocados por el uso de la información reutilizada.

El Ayuntamiento de Zaragoza no garantiza la continuidad en la puesta a disposición de los documentos reutilizables, ni en contenido ni en forma, ni asume responsabilidades por cualquier error u omisión contenido en ellos.
***** Responsabilidad del agente reutilizador

El agente reutilizador se haya sometido a la normativa aplicable en materia de reutilización de la información del sector público, incluyendo el régimen sancionador previsto en el artículo 11 de la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público.
*** Enlaces

Los enlaces contenidos en la sede electrónica del Excmo. Ayuntamiento de Zaragoza pueden dirigir a páginas web de terceros sobre las que el Excmo. Ayuntamiento de Zaragoza no ejerce ningún control, por lo que no asume ninguna responsabilidad por el contenido, informaciones o servicios que pudieran aparecer en dichos sitios y en consecuencia no será en ningún caso responsable de los daños y perjuicios que pudieran derivarse.
*** Ley aplicable y Jurisdicción

Para la resolución de todas las controversias o cuestiones relacionadas con la presente sede electrónica o de las actividades en ella desarrolladas, será de aplicación la legislación española, a la que se someten expresamente las partes, siendo competentes para la resolución de todos los conflictos derivados o relacionados con su uso los Juzgados y Tribunales de Zaragoza.
* Definicion de estrategia de nombrado de recursos
Hash URIs for ontological terms, slash URIs for individuals

+ Domain: http://www.example.net/
+ Ontological terms path: http://www.example.net/group42/ontology/estaciones#
+ Individual path: http://www.example.net/group42/resource
+ Ontological terms pattern: http://www.example.net/group42/ontology/estaciones#&lt;term_name&gt;
+ Individuals pattern: http://www.example.net/group42/resource/&lt;resource_type&gt;/&lt;resource_name&gt;
